dist: trusty
sudo: required

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-cmake-3.x
    packages:
      - gcc-6
      - g++-6
      - cmake-3.5.2

script:
  - export CXX=/usr/bin/g++-6
  - cd test
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ./ZipIterTests


notifications:
  email: false